print("Hello, today we will make a simple story together!")
print("first, tell me a bit about yourself")
print("What's your name?")
input()
print("That's a cool name")
print("My name is storyrobot")
print("Waduya think of my name?")
input()
print("Thanks, I guess")
input()
print("Anyway, let's get a move on, ready?")
input()
print("Ok, this will be simalar to a madlib")
animal = input("give me any type of animal")
country = input("name any country")
place = input("give me any place you would go to experience something")
verb = input("finally, give me any verb ending in an ed or that is past tense")
print("Alright, let me reveal the story! Ready?")
input()
print(f"Once upon a time, there was an {animal} who lived in {country}. The {animal}, he had one dream. He really wanted to go to the {place}. However, his parents never let him. Lucky for him, he had just turned 18. So, the {animal} decided to finally go to the {place}. When he got there, he didn't expect a guard to be waiting outside for him. The guard told him that he couldn't enter. the {animal} protested, but the guard wouldn't listen. In the end, the {animal} {verb} the guard, and ruined his chances of ever getting into the {place}, and was kicked out of {country}.")